"""add job_id and message to job history

Revision ID: 0496f39b1e64
Revises: af21229dc2ae
Create Date: 2026-04-19 19:08:36.833586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0496f39b1e64'
down_revision = 'af21229dc2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_history', schema=None) as batch_op:
        batch_op.drop_column('message')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
