"""add tmdb,imdb,tvdb columns to file_cache

Revision ID: 32696c475113
Revises: af2c8bd878ae
Create Date: 2026-03-23 20:00:13.062201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32696c475113'
down_revision = 'af2c8bd878ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imdb_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tmdb_id', sa.String(), nullable=True))

    with op.batch_alter_table('unmatched_shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imdb_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tmdb_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tvdb_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_shows', schema=None) as batch_op:
        batch_op.drop_column('tvdb_id')
        batch_op.drop_column('tmdb_id')
        batch_op.drop_column('imdb_id')

    with op.batch_alter_table('unmatched_movies', schema=None) as batch_op:
        batch_op.drop_column('tmdb_id')
        batch_op.drop_column('imdb_id')

    # ### end Alembic commands ###
