"""add notifier event table

Revision ID: 63093756b57a
Revises: 4e767a310e1a
Create Date: 2026-05-04 15:51:30.135636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63093756b57a'
down_revision = '4e767a310e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifier_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event', 'module', name='uq_notifier_event_module')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifier_event')
    # ### end Alembic commands ###
