"""add auth method and rename rclone db values

Revision ID: a1084944482c
Revises: f9e1b0f86c57
Create Date: 2026-03-09 19:02:20.334962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1084944482c'
down_revision = 'f9e1b0f86c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rclone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('client_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('auth_method', sa.String(), nullable=True))
        batch_op.drop_column('rclone_secret')
        batch_op.drop_column('rclone_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rclone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rclone_token', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rclone_secret', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('auth_method')
        batch_op.drop_column('client_secret')
        batch_op.drop_column('oauth_token')

    # ### end Alembic commands ###
