"""add is_configured flag to db for modules

Revision ID: aa70f6ec52c6
Revises: a1084944482c
Create Date: 2026-03-09 22:08:34.069434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa70f6ec52c6'
down_revision = 'a1084944482c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_renamerr_configured', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unmatched_assets_configured', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('plex_uploaderr_configured', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('drive_sync_configured', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_table', schema=None) as batch_op:
        batch_op.drop_column('drive_sync_configured')
        batch_op.drop_column('plex_uploaderr_configured')
        batch_op.drop_column('unmatched_assets_configured')
        batch_op.drop_column('poster_renamerr_configured')

    # ### end Alembic commands ###
