"""add instance, arr_id, tmdb_id, imdb_id, tvdb_id to file cache

Revision ID: ae421c71565c
Revises: 32696c475113
Create Date: 2026-03-23 21:59:46.172085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae421c71565c'
down_revision = '32696c475113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('arr_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tmdb_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imdb_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tvdb_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_cache', schema=None) as batch_op:
        batch_op.drop_column('tvdb_id')
        batch_op.drop_column('imdb_id')
        batch_op.drop_column('tmdb_id')
        batch_op.drop_column('arr_id')
        batch_op.drop_column('instance')

    # ### end Alembic commands ###
