"""add friendly_name column to gdrives

Revision ID: af2c8bd878ae
Revises: dcf1d3c96d80
Create Date: 2026-03-13 14:02:34.914481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2c8bd878ae'
down_revision = 'dcf1d3c96d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gdrives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendly_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gdrives', schema=None) as batch_op:
        batch_op.drop_column('friendly_name')

    # ### end Alembic commands ###
