"""add drive root column

Revision ID: c2967bd806fd
Revises: aa70f6ec52c6
Create Date: 2026-03-13 11:15:29.464075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2967bd806fd'
down_revision = 'aa70f6ec52c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_root', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_table', schema=None) as batch_op:
        batch_op.drop_column('drive_root')

    # ### end Alembic commands ###
