"""add drive type column

Revision ID: dcf1d3c96d80
Revises: c2967bd806fd
Create Date: 2026-03-13 11:53:26.264019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf1d3c96d80'
down_revision = 'c2967bd806fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gdrives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gdrives', schema=None) as batch_op:
        batch_op.drop_column('drive_type')

    # ### end Alembic commands ###
