"""initial

Revision ID: f9e1b0f86c57
Revises:
Create Date: 2026-03-03 22:19:50.134012

"""

import sqlalchemy as sa
from alembic import op

from daps_webui.models.file_cache import JSONEncodedText

# revision identifiers, used by Alembic.
revision = "f9e1b0f86c57"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "current_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(), nullable=True),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.Column("next_run", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_cache",
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("has_episodes", sa.Integer(), nullable=True),
        sa.Column("has_file", sa.Integer(), nullable=True),
        sa.Column("media_type", sa.String(), nullable=True),
        sa.Column("file_hash", sa.String(), nullable=True),
        sa.Column("original_file_hash", sa.String(), nullable=True),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.Column("border_replaced", sa.Integer(), nullable=False),
        sa.Column("border_setting", sa.String(), nullable=True),
        sa.Column("custom_color", sa.String(), nullable=True),
        sa.Column("webhook_run", sa.Integer(), nullable=True),
        sa.Column("uploaded_to_libraries", JSONEncodedText(), nullable=False),
        sa.Column("uploaded_editions", JSONEncodedText(), nullable=False),
        sa.PrimaryKeyConstraint("file_path"),
    )
    op.create_table(
        "gdrives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("drive_name", sa.String(), nullable=True),
        sa.Column("drive_id", sa.String(), nullable=True),
        sa.Column("drive_location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(), nullable=True),
        sa.Column("run_time", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("run_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plex_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_name", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "radarr_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_name", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rclone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("rclone_token", sa.String(), nullable=True),
        sa.Column("rclone_secret", sa.String(), nullable=True),
        sa.Column("service_account", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("module", sa.String(), nullable=True),
        sa.Column("schedule_type", sa.String(), nullable=True),
        sa.Column("schedule_value", sa.String(), nullable=True),
        sa.Column("next_run", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_level_unmatched_assets", sa.String(), nullable=False),
        sa.Column("log_level_poster_renamer", sa.String(), nullable=False),
        sa.Column("log_level_plex_uploaderr", sa.String(), nullable=False),
        sa.Column("log_level_border_replacerr", sa.String(), nullable=False),
        sa.Column("log_level_drive_sync", sa.String(), nullable=False),
        sa.Column("poster_root", sa.String(), nullable=True),
        sa.Column("target_path", sa.String(), nullable=True),
        sa.Column("source_dirs", sa.String(), nullable=True),
        sa.Column("library_names", sa.String(), nullable=True),
        sa.Column("asset_folders", sa.Integer(), nullable=False),
        sa.Column("clean_assets", sa.Integer(), nullable=False),
        sa.Column("unmatched_assets", sa.Integer(), nullable=False),
        sa.Column("replace_border", sa.Integer(), nullable=False),
        sa.Column("border_setting", sa.String(), nullable=True),
        sa.Column("custom_color", sa.String(), nullable=True),
        sa.Column("run_single_item", sa.Integer(), nullable=False),
        sa.Column("only_unmatched", sa.Integer(), nullable=False),
        sa.Column("upload_to_plex", sa.Integer(), nullable=False),
        sa.Column("match_alt", sa.Integer(), nullable=False),
        sa.Column("drive_sync", sa.Integer(), nullable=False),
        sa.Column("reapply_posters", sa.Integer(), nullable=False),
        sa.Column("show_all_unmatched", sa.Integer(), nullable=False),
        sa.Column("disable_unmatched_collections", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sonarr_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_name", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "unmatched_collections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "unmatched_movies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=True),
        sa.Column("instance", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "unmatched_shows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=True),
        sa.Column("main_poster_missing", sa.Integer(), nullable=False),
        sa.Column("instance", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "unmatched_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total_movies", sa.Integer(), nullable=False),
        sa.Column("total_series", sa.Integer(), nullable=False),
        sa.Column("total_seasons", sa.Integer(), nullable=False),
        sa.Column("total_collections", sa.Integer(), nullable=False),
        sa.Column("unmatched_movies", sa.Integer(), nullable=False),
        sa.Column("unmatched_series", sa.Integer(), nullable=False),
        sa.Column("unmatched_seasons", sa.Integer(), nullable=False),
        sa.Column("unmatched_collections", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "webhook_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("item_name", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_type", "item_name", name="unique_item_type_name"),
    )
    op.create_table(
        "unmatched_seasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["show_id"], ["unmatched_shows.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("show_id", "season", name="unique_show_season"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unmatched_seasons")
    op.drop_table("webhook_cache")
    op.drop_table("unmatched_stats")
    op.drop_table("unmatched_shows")
    op.drop_table("unmatched_movies")
    op.drop_table("unmatched_collections")
    op.drop_table("sonarr_instances")
    op.drop_table("settings_table")
    op.drop_table("schedule")
    op.drop_table("rclone")
    op.drop_table("radarr_instances")
    op.drop_table("plex_instances")
    op.drop_table("job_history")
    op.drop_table("gdrives")
    op.drop_table("file_cache")
    op.drop_table("current_jobs")
    # ### end Alembic commands ###
