services:
  postarr:
    container_name: # postarr
    image: # ghcr.io/zarskie/postarr
    environment:
      # - TZ=America/Vancouver
      # - PUID=99
      # - PGID=100
    ports:
      # - "8000:8000"
    volumes:
      # - path to config directory:/config
      # - path to poster folders:/posters
      # - path to kometa asset folder:/assets
